version: '3'

services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    ports:
      - 15432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vendingmachine


